### ISSUE TITLE
Bookmarks Bar

### ISSUE THREAD

**Issue by thelawrencearm** [GabeVilela/Vivaldi-GX#10]
I removed the Bookmarks-bar because from the ModSettings.  The accent color contrast was screwing with my eyes.  However, doing sow caused the bookmarks bar to merge over the line.  

![image](https://user-images.githubusercontent.com/20508294/117672437-76f22900-b16f-11eb-9b44-6017029f094e.png)

**Comment by GabeVilela** [comment]
This isn't a bug.
Removing stuff from mod settings disables every modification by the mod for that UI component.
That's why the bookmarks bar returned to its default stylization.
