### ISSUE TITLE
Panel line on left side pops out when in full screen mode

### ISSUE THREAD

**Issue by Apocolypto** [GabeVilela/Vivaldi-GX#17]
Whenever in full screen mode for any video, a little bit of the left panel line is shown on the left side of the video as you can see in the screenshot provided. 

Once you see it, you can't unsee it. It shouldn't serve as a major distraction from the video itself but I can't help but notice that it's present each and every time. 

A fix for this would be greatly appreciated!

![panel line](https://user-images.githubusercontent.com/96832036/161381006-350d8512-af0f-43f7-badb-3bb9331ddede.png)

**Comment by GabeVilela** [comment]
Replace the contents of `sources/sidebar.css` with [this](https://raw.githubusercontent.com/GabeVilela/Vivaldi-GX/54b27de70ce84a50ba1f4d187e1d97081a611b24/Mod/sources/sidebar.css) and let me know if it works.

**Comment by Apocolypto** [comment]
It worked perfectly, thanks!
