### ISSUE TITLE
sidebar width issue

### ISSUE THREAD

**Issue by alok-old** [GabeVilela/Vivaldi-GX#5]
By watching the screenshot you can actually see the issue. Btw, thanks for creating this

![Screenshot (129)](https://user-images.githubusercontent.com/67475527/103772813-197a8e00-5050-11eb-94ba-d4fbbe0758f6.png)

**Comment by GabeVilela** [comment]
That's not a bug. You shouldn't be using the sidebar activator with this mod
Settings > Panel > Switch off "Show Panel Toggle"
