### ISSUE TITLE
Left panel

### ISSUE THREAD

**Issue by xWqNN** [GabeVilela/Vivaldi-GX#6]
![image](https://user-images.githubusercontent.com/60393554/108233062-75a6f680-7154-11eb-8766-a4d239893904.png)
When I close the panel, it became a line like this and I hate it. Can you make something like the line ending at the end of the adressbar and maybe continue from under of address bar something like that. Without that, this theme is amazing, thnx for this theme <3.

**Comment by GabeVilela** [comment]
It looks like this due to some limitations, but once they get removed by Vivaldi devs, I'll rework on this.
This is how it should have been
![image](https://user-images.githubusercontent.com/49645243/108249645-10430d80-7134-11eb-8eab-c4a3234f451e.png)

**Comment by xWqNN** [comment]
Actually I said this for symmetry patients. If they see the line like that they can be very angry or another thing i don't know. I just wanted to tell can you clear this line
![vivaldigxissue](https://user-images.githubusercontent.com/60393554/108378487-17dae300-7216-11eb-92ef-d9a30c7089a7.png)

**Comment by GabeVilela** [comment]
I don't plan to change it.
You can remove the code between the lines 113 - 128 in "sidebar.css" and that line will be gone.
