### ISSUE TITLE
Auto-Update Script

### ISSUE THREAD

**Issue by hofq** [GabeVilela/Vivaldi-GX#8]
Hey There,
 I wonder if something like an Auto-Update Script would be possible, so that you dont need to manually update the Skin/Theme if Vivialdi throughs an Update at you.

(I love the Skin btw.)

**Comment by GabeVilela** [comment]
You can add this project to your watch list and clone this repository through git.
When there's an update, you'll be notified through GitHub, and to download it, a simple git fetch command should do the trick.

**Comment by hofq** [comment]
> You can add this project to your watch list and clone this repository through git.
> When there's an update, you'll be notified through GitHub, and to download it, a simple git fetch command should do the trick.

Nice, thx
